server:
  port: 8075



spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
  application:
    name: gateway-server


  #      routes:
  #        - id: projectModule
  #          uri: lb://PROJECT-SERVICE
  #          predicates:
  #            - Path=/api/**
#        - id: consumerModule
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/consumer/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, gateway

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    ma.egilekom.api.gatewayservice: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: DEBUG

